import { Info } from "lucide-react";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

type Variant = "self-reported" | "ai-scored" | "estimated";

const CONFIG: Record<Variant, { label: string; tip: string; classes: string }> = {
  "self-reported": {
    label: "Self-reported",
    tip: "Entered manually by the creator — not independently verified.",
    classes: "text-amber-600 bg-amber-50 border-amber-200 dark:bg-amber-950/30 dark:border-amber-800",
  },
  "ai-scored": {
    label: "AI-scored",
    tip: "Generated by the Cohesiq matching engine using weighted signals. Not a guarantee of performance.",
    classes: "text-purple-600 bg-purple-50 border-purple-200 dark:bg-purple-950/30 dark:border-purple-800",
  },
  "estimated": {
    label: "Estimated",
    tip: "Computed from available data. Actual results may vary.",
    classes: "text-blue-600 bg-blue-50 border-blue-200 dark:bg-blue-950/30 dark:border-blue-800",
  },
};

interface EstimatedTagProps {
  variant?: Variant;
}

export function EstimatedTag({ variant = "estimated" }: EstimatedTagProps) {
  const { label, tip, classes } = CONFIG[variant];
  return (
    <TooltipProvider delayDuration={200}>
      <Tooltip>
        <TooltipTrigger asChild>
          <span className={`inline-flex items-center gap-0.5 rounded border px-1 py-0.5 text-[10px] font-medium leading-none cursor-default ${classes}`}>
            {label}
            <Info className="h-2.5 w-2.5" />
          </span>
        </TooltipTrigger>
        <TooltipContent side="top" className="max-w-[200px] text-xs">
          {tip}
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}
