"""add_ai_match_scores_table

Revision ID: 53f8d9a8a155
Revises: 0012
Create Date: 2026-05-30 04:47:52.524653+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53f8d9a8a155'
down_revision: Union[str, None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_match_scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('score_niche', sa.Float(), nullable=True),
    sa.Column('score_engagement', sa.Float(), nullable=True),
    sa.Column('score_budget', sa.Float(), nullable=True),
    sa.Column('score_language', sa.Float(), nullable=True),
    sa.Column('score_total', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['creator_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'creator_id', name='uq_campaign_creator_match')
    )
    op.alter_column('brand_profiles', 'country_code',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               nullable=False,
               existing_server_default=sa.text("'BD'::bpchar"))
    op.alter_column('brand_profiles', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('brand_profiles', 'total_campaigns',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_brand_profiles_niche', table_name='brand_profiles')
    op.drop_index('idx_brand_profiles_user', table_name='brand_profiles')
    op.drop_index('idx_applications_campaign', table_name='campaign_applications')
    op.drop_index('idx_applications_creator', table_name='campaign_applications')
    op.drop_index('idx_applications_creator_status', table_name='campaign_applications')
    op.drop_index('idx_applications_status', table_name='campaign_applications')
    op.drop_constraint('uq_application_campaign_creator', 'campaign_applications', type_='unique')
    op.alter_column('campaign_deliverable_requirements', 'quantity',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text("'1'::smallint"))
    op.drop_index('idx_deliverable_req_campaign', table_name='campaign_deliverable_requirements')
    op.alter_column('campaign_language_targets', 'language_code',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.alter_column('campaign_language_targets', 'is_required',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('campaigns', 'required_platforms',
               existing_type=postgresql.ARRAY(postgresql.ENUM('youtube', 'instagram', 'facebook', 'tiktok', 'twitter_x', 'linkedin', 'snapchat', 'other', name='platform_type')),
               nullable=False,
               existing_server_default=sa.text("'{youtube}'::platform_type[]"))
    op.alter_column('campaigns', 'creator_min_followers',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1000'))
    op.alter_column('campaigns', 'target_countries',
               existing_type=postgresql.ARRAY(sa.CHAR(length=2)),
               type_=sa.ARRAY(sa.String(length=2)),
               nullable=False,
               existing_server_default=sa.text("'{BD}'::bpchar[]"))
    op.alter_column('campaigns', 'target_cities',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('campaigns', 'number_of_creators',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index('idx_campaigns_active', table_name='campaigns', postgresql_where="(status = 'active'::campaign_status)")
    op.drop_index('idx_campaigns_brand', table_name='campaigns')
    op.drop_index('idx_campaigns_budget', table_name='campaigns')
    op.drop_index('idx_campaigns_primary_niche', table_name='campaigns')
    op.drop_index('idx_campaigns_status', table_name='campaigns')
    op.drop_index('idx_collab_history_brand', table_name='creator_collaboration_history')
    op.drop_index('idx_collab_history_creator', table_name='creator_collaboration_history')
    op.alter_column('creator_languages', 'language_code',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.alter_column('creator_languages', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('creator_niches', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_creator_niches_niche', table_name='creator_niches')
    op.alter_column('creator_portfolio_items', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('creator_portfolio_items', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_portfolio_creator', table_name='creator_portfolio_items')
    op.alter_column('creator_profiles', 'country_code',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               nullable=False,
               existing_server_default=sa.text("'BD'::bpchar"))
    op.alter_column('creator_profiles', 'timezone',
               existing_type=sa.VARCHAR(length=60),
               nullable=False,
               existing_server_default=sa.text("'Asia/Dhaka'::character varying"))
    op.alter_column('creator_profiles', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('creator_profiles', 'response_time_hours',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('48'))
    op.alter_column('creator_profiles', 'preferred_collaboration_types',
               existing_type=postgresql.ARRAY(postgresql.ENUM('sponsored_post', 'product_review', 'brand_ambassador', 'affiliate', 'gifted_product', 'event_coverage', 'other', name='collaboration_type')),
               nullable=False,
               existing_server_default=sa.text("'{}'::collaboration_type[]"))
    op.alter_column('creator_profiles', 'is_identity_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('creator_profiles', 'total_collaborations',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_creator_profiles_avail', table_name='creator_profiles')
    op.drop_index('idx_creator_profiles_city', table_name='creator_profiles')
    op.drop_index('idx_creator_profiles_country', table_name='creator_profiles')
    op.drop_index('idx_creator_profiles_user', table_name='creator_profiles')
    op.alter_column('creator_rate_cards', 'is_negotiable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('creator_rate_cards', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index('idx_rate_cards_creator', table_name='creator_rate_cards')
    op.drop_constraint('uq_rate_card_creator_platform_deliverable', 'creator_rate_cards', type_='unique')
    op.alter_column('creator_social_profiles', 'is_primary_platform',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('creator_social_profiles', 'is_monetized',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('creator_social_profiles', 'has_verified_badge',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('creator_social_profiles', 'audience_country_primary',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=True,
               existing_server_default=sa.text("'BD'::bpchar"))
    op.alter_column('creator_social_profiles', 'content_languages',
               existing_type=postgresql.ARRAY(sa.CHAR(length=2)),
               type_=sa.ARRAY(sa.String(length=2)),
               nullable=False,
               existing_server_default=sa.text("'{bn}'::bpchar[]"))
    op.drop_index('idx_social_niche_followers', table_name='creator_social_profiles', postgresql_where='(follower_count IS NOT NULL)')
    op.drop_index('idx_social_profiles_creator', table_name='creator_social_profiles')
    op.drop_index('idx_social_profiles_engagement', table_name='creator_social_profiles')
    op.drop_index('idx_social_profiles_followers', table_name='creator_social_profiles')
    op.drop_index('idx_social_profiles_platform', table_name='creator_social_profiles')
    op.drop_constraint('uq_social_creator_platform', 'creator_social_profiles', type_='unique')
    op.alter_column('languages', 'code',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('languages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('niches', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('niches', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('niches', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('niches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('niches_parent_id_fkey', 'niches', type_='foreignkey')
    op.alter_column('reviews', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index('idx_reviews_application', table_name='reviews')
    op.drop_index('idx_reviews_reviewee_brand', table_name='reviews')
    op.drop_index('idx_reviews_reviewee_creator', table_name='reviews')
    op.drop_constraint('uq_review_brand', 'reviews', type_='unique')
    op.drop_constraint('uq_review_creator', 'reviews', type_='unique')
    op.drop_index('idx_users_clerk_id', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_clerk_id', 'users', ['clerk_id'], unique=False)
    op.create_unique_constraint('uq_review_creator', 'reviews', ['application_id', 'reviewer_creator_id'])
    op.create_unique_constraint('uq_review_brand', 'reviews', ['application_id', 'reviewer_brand_id'])
    op.create_index('idx_reviews_reviewee_creator', 'reviews', ['reviewee_creator_id'], unique=False)
    op.create_index('idx_reviews_reviewee_brand', 'reviews', ['reviewee_brand_id'], unique=False)
    op.create_index('idx_reviews_application', 'reviews', ['application_id'], unique=False)
    op.alter_column('reviews', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_foreign_key('niches_parent_id_fkey', 'niches', 'niches', ['parent_id'], ['id'], ondelete='SET NULL')
    op.alter_column('niches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('niches', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('niches', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('niches', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('languages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('languages', 'code',
               existing_type=sa.String(),
               type_=sa.CHAR(length=2),
               existing_nullable=False)
    op.create_unique_constraint('uq_social_creator_platform', 'creator_social_profiles', ['creator_id', 'platform'])
    op.create_index('idx_social_profiles_platform', 'creator_social_profiles', ['platform'], unique=False)
    op.create_index('idx_social_profiles_followers', 'creator_social_profiles', ['follower_count'], unique=False)
    op.create_index('idx_social_profiles_engagement', 'creator_social_profiles', ['engagement_rate'], unique=False)
    op.create_index('idx_social_profiles_creator', 'creator_social_profiles', ['creator_id'], unique=False)
    op.create_index('idx_social_niche_followers', 'creator_social_profiles', ['platform', 'follower_count'], unique=False, postgresql_where='(follower_count IS NOT NULL)')
    op.alter_column('creator_social_profiles', 'content_languages',
               existing_type=sa.ARRAY(sa.String(length=2)),
               type_=postgresql.ARRAY(sa.CHAR(length=2)),
               nullable=True,
               existing_server_default=sa.text("'{bn}'::bpchar[]"))
    op.alter_column('creator_social_profiles', 'audience_country_primary',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               existing_nullable=True,
               existing_server_default=sa.text("'BD'::bpchar"))
    op.alter_column('creator_social_profiles', 'has_verified_badge',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('creator_social_profiles', 'is_monetized',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('creator_social_profiles', 'is_primary_platform',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_unique_constraint('uq_rate_card_creator_platform_deliverable', 'creator_rate_cards', ['creator_id', 'platform', 'deliverable_type'])
    op.create_index('idx_rate_cards_creator', 'creator_rate_cards', ['creator_id'], unique=False)
    op.alter_column('creator_rate_cards', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('creator_rate_cards', 'is_negotiable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index('idx_creator_profiles_user', 'creator_profiles', ['user_id'], unique=False)
    op.create_index('idx_creator_profiles_country', 'creator_profiles', ['country_code'], unique=False)
    op.create_index('idx_creator_profiles_city', 'creator_profiles', ['city'], unique=False)
    op.create_index('idx_creator_profiles_avail', 'creator_profiles', ['is_available'], unique=False)
    op.alter_column('creator_profiles', 'total_collaborations',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('creator_profiles', 'is_identity_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('creator_profiles', 'preferred_collaboration_types',
               existing_type=postgresql.ARRAY(postgresql.ENUM('sponsored_post', 'product_review', 'brand_ambassador', 'affiliate', 'gifted_product', 'event_coverage', 'other', name='collaboration_type')),
               nullable=True,
               existing_server_default=sa.text("'{}'::collaboration_type[]"))
    op.alter_column('creator_profiles', 'response_time_hours',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('48'))
    op.alter_column('creator_profiles', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('creator_profiles', 'timezone',
               existing_type=sa.VARCHAR(length=60),
               nullable=True,
               existing_server_default=sa.text("'Asia/Dhaka'::character varying"))
    op.alter_column('creator_profiles', 'country_code',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               nullable=True,
               existing_server_default=sa.text("'BD'::bpchar"))
    op.create_index('idx_portfolio_creator', 'creator_portfolio_items', ['creator_id'], unique=False)
    op.alter_column('creator_portfolio_items', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('creator_portfolio_items', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index('idx_creator_niches_niche', 'creator_niches', ['niche_id'], unique=False)
    op.alter_column('creator_niches', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('creator_languages', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('creator_languages', 'language_code',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               existing_nullable=False)
    op.create_index('idx_collab_history_creator', 'creator_collaboration_history', ['creator_id'], unique=False)
    op.create_index('idx_collab_history_brand', 'creator_collaboration_history', ['brand_id'], unique=False)
    op.create_index('idx_campaigns_status', 'campaigns', ['status'], unique=False)
    op.create_index('idx_campaigns_primary_niche', 'campaigns', ['primary_niche_id'], unique=False)
    op.create_index('idx_campaigns_budget', 'campaigns', ['budget_per_creator_max'], unique=False)
    op.create_index('idx_campaigns_brand', 'campaigns', ['brand_id'], unique=False)
    op.create_index('idx_campaigns_active', 'campaigns', ['status', 'application_deadline'], unique=False, postgresql_where="(status = 'active'::campaign_status)")
    op.alter_column('campaigns', 'number_of_creators',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('campaigns', 'target_cities',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('campaigns', 'target_countries',
               existing_type=sa.ARRAY(sa.String(length=2)),
               type_=postgresql.ARRAY(sa.CHAR(length=2)),
               nullable=True,
               existing_server_default=sa.text("'{BD}'::bpchar[]"))
    op.alter_column('campaigns', 'creator_min_followers',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1000'))
    op.alter_column('campaigns', 'required_platforms',
               existing_type=postgresql.ARRAY(postgresql.ENUM('youtube', 'instagram', 'facebook', 'tiktok', 'twitter_x', 'linkedin', 'snapchat', 'other', name='platform_type')),
               nullable=True,
               existing_server_default=sa.text("'{youtube}'::platform_type[]"))
    op.alter_column('campaign_language_targets', 'is_required',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('campaign_language_targets', 'language_code',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               existing_nullable=False)
    op.create_index('idx_deliverable_req_campaign', 'campaign_deliverable_requirements', ['campaign_id'], unique=False)
    op.alter_column('campaign_deliverable_requirements', 'quantity',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text("'1'::smallint"))
    op.create_unique_constraint('uq_application_campaign_creator', 'campaign_applications', ['campaign_id', 'creator_id'])
    op.create_index('idx_applications_status', 'campaign_applications', ['status'], unique=False)
    op.create_index('idx_applications_creator_status', 'campaign_applications', ['creator_id', 'status'], unique=False)
    op.create_index('idx_applications_creator', 'campaign_applications', ['creator_id'], unique=False)
    op.create_index('idx_applications_campaign', 'campaign_applications', ['campaign_id'], unique=False)
    op.create_index('idx_brand_profiles_user', 'brand_profiles', ['user_id'], unique=False)
    op.create_index('idx_brand_profiles_niche', 'brand_profiles', ['niche_id'], unique=False)
    op.alter_column('brand_profiles', 'total_campaigns',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('brand_profiles', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('brand_profiles', 'country_code',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               nullable=True,
               existing_server_default=sa.text("'BD'::bpchar"))
    op.drop_table('ai_match_scores')
    # ### end Alembic commands ###
